spring:
  application:
    name: excel-to-ics
logging:
    level:
      root: INFO
      '[org.springframework.web]': INFO
      '[org.springframework.web.filter.CommonsRequestLoggingFilter]': DEBUG
    file:
      path: logs/excel-to-ics.log
    logback: 
      rollingpolicy: 
        max-history: 10
        max-file-size: 100MB
        total-size-cap: 1GB


